services:
  - type: web
    name: himigtube
    env: python
    buildCommand: |
      pip install -r requirements.txt
      sudo apt-get install ffmpeg
    startCommand: gunicorn himigtube.wsgi
    plan: free
